sudo: required
language: java
jdk: oraclejdk8

before_install:
  - ./Klinicki-centar/chmod +x mvnw

addons:
 sonarcloud:
 organization: tim19
 token: bd5e21c61e921f61bab61f7e27518c4810286ee8
 
script:
 - ./Klinicki-centar/mvnw clean install -DskipTests=false -B
 - ./Klinicki-centar/mvnw sonar:sonar -Dsonar.projectKey=$PROJECT_KEY -Dsonar.organization=stojkovm-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN


dist: trusty

deploy:
  provider: heroku
  api_key: d067026a-edce-4d85-b8cb-6124fb854a8a
  app: mrsisa2020-t19

