sudo: required
language: java
jdk: oraclejdk8

addons:
 sonarcloud:
 organization: tim19
 token: bd5e21c61e921f61bab61f7e27518c4810286ee8
 
script:
./build.sh

dist: trusty

deploy:
  provider: heroku
  api_key: d067026a-edce-4d85-b8cb-6124fb854a8a
  app: mrsisa2020-t19

