sudo: required
language: java
jdk: oraclejdk8

before_install:
  - chmod +x ./Klinicki-centar/mvnw

addons:
 sonarcloud:
 organization: tim19
 token: bd5e21c61e921f61bab61f7e27518c4810286ee8
 
script:
 - ./Klinicki-centar/mvnw clean install -D skipTests=false -B
 - ./Klinicki-centar/mvnw sonar:sonar -D sonar.projectKey=cigor99_MRSISA2020_T19 -D sonar.organization=tim19 -D sonar.host.url=https://sonarcloud.io -D sonar.login=bd5e21c61e921f61bab61f7e27518c4810286ee8


dist: trusty

deploy:
  provider: heroku
  api_key: d067026a-edce-4d85-b8cb-6124fb854a8a
  app: mrsisa2020-t19

