package MRSISA.Klinicki.centar.domain;

public enum StanjePacijenta {
	PRIHVACEN, NA_CEKANJU, AKTIVAN, ODBIJEN
}
//PRIHVACEN ZNACI DA JOS NIJE POTVRDIO AKTIVACIJU IZ EMAIL-A
//NA CEKANJU ZNACI DA SE CEKA ODOBRENJE ADMINA
